config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	resources :tweets #routes are evaluated by priority
  
  get '/about' => 'pages#about'
	get '/another' => 'pages#another'
	root 'pages#index' #get '/' => 'pages/index' #root usually at the bottom

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

	def about
		@content = 'Tweeter is better than Twitter.'
		render 'fancypage'
	end

	def another
		@content = 'This is another page'
		render 'fancypage'
	end


end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	def new
		@tweet = Tweet.new
	end 
	
	def create
		@tweet = Tweet.new
		@tweet.content = params [:tweet][:content]
		@tweet.posted_on = DateTime.now
		@tweet.user = User.current_user

		@tweet.save!
		redirect_to :action => :index
	end

	def index
		@tweets = User.current_user.tweets
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
		@user = User.new
  end

  def create
		@user = User.new
		@user.username = params[:user][:username]
		@user.password = params[:user][:password]
		@user.save!
		redirect_to :action => :index
  end

	def index
		@users = User.all	
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])	
	end

	def update
		@user = User.find(params[:id])
		@user.username = params[:user][:username]
		@user.password = params[:user][:password]
		@user.save!
		redirect_to :action => :index	
	end
	
	def destroy
		@user = User.find(params[:id])
		@user.destroy!
		redirect_to :action => :index	
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tweeter" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#"><%= yield :header %></a>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "Home", "/"  %></li>
                <li><%= link_to "About", "/about"  %></li>
                <li><%= link_to "Another", "/another"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
	 <br> <br> <br>
    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Menu</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Click on a link to go there</li>
                <li><%= link_to "Home", "/"  %></li>
                <li><%= link_to "About", "/about"  %></li>
                <li><%= link_to "Another", "/another"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
	   <%= yield :footer %>
        <p>&copy; By Kim</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/another.html.erb
<h1><%= @data %></h1>

app/views/pages/fancypage.html.erb
<h1> This is a fancy page. </h1>
<p> <%= @content %> </p>

<%= content_for :header do %>
	Tweeter is so fancy
<% end %>

<%= content_for :footer do %>
	<p> <%= link_to 'Go to Twitter instead', 'http://www.twitter.com'%> </p>
<% end %>

app/views/pages/hi.html.erb
<h1>Hello World</h1>
<p>This is the actual file.</p>
<%= link_to 'Another', '/hello' %>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<p> <%= link_to 'Twitter', 'http://www.twitter.com'%> </p>

<%= content_for :header do %>
	Tweeter is so awesome
<% end %>

<%= content_for :footer do %>
	This is my footer
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :posted_on %><br>
    <%= f.datetime_select :posted_on %>
  </div>
  <div class="field">
    <%= f.label :tweeter %><br>
    <%= f.text_field :tweeter %>
  </div>
  <div class="field">
    <%= f.label :likes %><br>
    <%= f.number_field :likes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Tweets for <%= User.current_user %></h1>
<% @tweets.each do |tweet| %>
	<div class="well">
		<p><%=tweet.content %></p>
	</div>
<%end%> <!-- place = sign only when you are displaying output -->

app/views/tweets/new.html.erb
<%= simple_form_for @tweet do |f|%>
	<%= f.input :content, :as => :text %>
	<%= f.input :posted_on %>
	<%= f.input :user_id %>
	<%=f.submit %>
<%end%>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @tweet.content %>
</p>

<p>
  <strong>Posted on:</strong>
  <%= @tweet.posted_on %>
</p>

<p>
  <strong>Tweeter:</strong>
  <%= @tweet.tweeter %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @tweet.likes %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p><%= debug @user %></p>

app/views/users/edit.html.erb
<%= content_for :header do %>
	Tweeter
<% end %>

<h1>Editing User</h1>
<%= form_for @user do |f| %>
	<%= f.label :username %>
	<%= f.text_field :username %>
	<br />
	<%= f.label :password %>
	<%= f.password_field :password %>
	<br />
	<%= f.submit 'Save' %>
<% end %>

<%= content_for :footer do %>
	Java nice day
<% end %>

app/views/users/index.html.erb
<table class="table">
	<thead>
		<tr>
			<td>ID</td>
			<td>Username</td>
			<td>Password</td>
			<td>Edit</td>
			<td>Delete</td>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>		
		<tr>
			<td><%= user.id %></td>
			<td><%= link_to user.username, user %></td>
			<td><%= user.password %></td>
			<td><%= link_to 'Edit', edit_user_path(user.id) %></td>
			<td><%= link_to 'DESTROY!!', user, :method => :delete %></td>
			
		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to 'Create New User', new_user_path %>

app/views/users/new.html.erb
<%= content_for :header do %>
	Tweeter
<% end %>

<h1>Create a new user</h1>
<%= form_for @user do |f| %>
	<%= f.label :username %>
	<%= f.text_field :username %>
	<br />
	<%= f.label :password %>
	<%= f.password_field :password %>
	<br />
	<%= f.submit 'Save' %>
<% end %>
<!--automatic na punta sa fields of model-->

<%= content_for :footer do %>
	Java nice day
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<p>My ID number is <%= @user.id %></p>
<p>My Password is <%= @user.password %></p>
<%= link_to 'Go back to list of users' , users_path %>